
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'AppDevelopExample' do
#pod 'AppDevelopModule', :git => 'https://github.com/1253463220/AppDevelopModule.git'
pod 'AppDevelopModule'
#pod 'QMUIKit/QMUIComponents/QMUIBadge'
#pod 'QMUIKit/QMUIComponents/QMUIEmptyView'

end
