
platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'AppDevelopExample' do
#pod 'AppDevelopModule', :git => 'https://github.com/1253463220/AppDevelopModule.git'
pod 'AppDevelopModule', :path => ".."
pod 'ZFPlayer', '~> 4.0'
pod 'ZFPlayer/ControlView', '~> 4.0'
pod 'ZFPlayer/AVPlayer', '~> 4.0'
end
